### ISSUE TITLE
design proposal

### ISSUE THREAD

**Issue by MadameLeRenoir** [tddbin/es6katas.org#1]
![kataes6](https://cloud.githubusercontent.com/assets/2222223/7211560/3ce1cb7a-e55c-11e4-82d3-a08fdd7e2cad.jpg)

**Comment by tddbin** [comment]
how cool is that?

--
Kind regards / Saludos / Mit freundlichen Grüßen
Things we think are important http://www.uxebu.com/universe/
Meet uxebus at http://www.uxebu.com/about-us/events/

Wolfram Kriesing, CTO
uxebu

kriesing@uxebu.com, mobile: +49 174 300 4595

uxebu GmbH
Fraunhofer Straße 31e
86167 Augsburg

Amtsgericht Augsburg, Handelsregister HRB 28613
Directors: W. Kriesing, T. v. Klipstein

**Comment by MadameLeRenoir** [comment]
Wolfram Thank you! Use it.
