### ISSUE TITLE
Make clearer that the class is included

### ISSUE THREAD

**Issue by caseywatts** [tddbin/es6katas.org#11]
In the [Arrow Functions Function Binding kata](http://tddbin.com/#?kata=es6/language/arrow-functions/binding) it took me a while to discover the `LexicallyBound' class at the bottom of the file in this kata. Normally I just do kata sequentially, I don't read ahead. It would help a bunch to either

1. have the class defined at the top of the file, or
2. to have a note at the top mentioning to read below

(ps I <3 this! just trying to be helpful :D)

**Comment by wolframkriesing** [comment]
good input, how about this change?
https://github.com/tddbin/katas/commit/38f6c33cda5e77d97a5b0ad7e06f327606f6d151
