### ISSUE TITLE
Call super() before "this" is used

### ISSUE THREAD

**Issue by GastonRosso** [tddbin/es6katas.org#12]
In the kata regarding to the use of super() inside constructors, specifically this:

```javascript
it('it is important where you place your `super()` call!', () => {
    class A {constructor() { this.countUp = 1; }}
    class B extends A {
      constructor() { 
        super(); 
        this.countUp = 2;   
      }
    }
    
    assert.equal(new B().countUp, 1);
  });
```

The suggested solution is to place the super() call after the reassignment of this.countUp, which I think is forbidden by the final semantics of classes. (See: http://www.2ality.com/2015/02/es6-classes-final.html in the part which talks about super-constructor calls).

Thank you!

**Comment by wolframkriesing** [comment]
thanks for finding this, the old version of babel allowed for it, fixed the kata and updated to new babel
Do you like this better? https://github.com/tddbin/katas/commit/7473c5bbabce535735934291ff1d270170018817

**Comment by GastonRosso** [comment]
Awesome! Thank you for your work.
