### ISSUE TITLE
Build on Linux

### ISSUE THREAD

**Issue by akoskm** [tddbin/es6katas.org#13]
This is based on a previous discussion here: Based on https://github.com/tddbin/es6katas.org/issues/8#issuecomment-117972767. Rebuilding doesn't work on Linux.

Once this is fixed a quick introduction in README.md would be great.

**Comment by wolframkriesing** [comment]
can you please give some details, how it fails, maybe a log. thx

**Comment by akoskm** [comment]
It doesn't fail but returns with a todo message: https://github.com/tddbin/katas/blob/master/scripts/build-for-offline.sh#L13.

**Comment by akoskm** [comment]
Looking at the build process you're trying to copy the `vendor` directory https://github.com/tddbin/katas/blob/master/scripts/build-for-offline.sh#L6 which isn't created in any of the previous steps.

**Comment by akoskm** [comment]
Any idea where it should be created or what's missing?

**Comment by wolframkriesing** [comment]
Could you have a look please if that works now?
https://github.com/tddbin/katas/commit/ed018c143f076fd3ece5f6e01870cece8b6201f5

**Comment by wolframkriesing** [comment]
Would be cool if you could post katas issues in that repo too. Thanks a lot.
I know its kinda hard to keep them apart :)
Thanks for your patience

**Comment by akoskm** [comment]
It fails because it can't find the `vendor` directory, I mentioned that earlier:

```
> katas@0.0.1 build-for-offline /home/akoskm/Projects/katas
> npm run build && ./scripts/build-for-offline.sh


> katas@0.0.1 build /home/akoskm/Projects/katas
> ./scripts/build.sh

cp: cannot stat ‘./vendor’: No such file or directory
```

**Comment by wolframkriesing** [comment]
I tried to install it on linux, first I get a compile error somewhere.
Than I can run the `npm run build-for-offline` and it fails with the error that it cant find `babel-node`.
Do you have that too?

```
$ npm run build-for-offline

> katas@0.0.1 build-for-offline /home/cain/work/uxebu/katas
> npm run build && ./scripts/build-for-offline.sh


> katas@0.0.1 build /home/cain/work/uxebu/katas
> ./scripts/build.sh

./scripts/build.sh: line 21: babel-node: command not found
cp: cannot stat ‘./vendor’: No such file or directory
```

**Comment by wolframkriesing** [comment]
oh man, was this tricky :) in the .gitignore I had 'dist' in there and the only dir in vendor where i file existed was 'bla/bla/dist' ... thanks for the help and reporting it, fixed it here 
https://github.com/tddbin/katas/commit/a09b8bd51d2d2dcb9eed0e8b16cc344cd118303a

**Comment by akoskm** [comment]
I can confirm this, the build passes.

My original intention was to make a local build and extend the es6katas page with links to relevant documentation. However, I haven't figured out yet how the development process looks in katas/es6katas.

I can't find any task or script which is intended for running a development instance of katas. Can you give us any directions?

**Comment by wolframkriesing** [comment]
yeah that is still a weak point :( 
I rarely do that but am a big fan of having it work too, currently I do it like this:
1) I comment out https://github.com/tddbin/es6katas.org/blob/master/src/browser/index.js#L17-L20 and comment in line 22
2) update this file https://github.com/tddbin/es6katas.org/blob/master/src/for-offline/grouped-metadata.json with the latest from http://katas.tddbin.com/katas/es6/language/__grouped__.json

If it doesnt work let me know

**Comment by wolframkriesing** [comment]
the `build-for-offline` is actually meant to really work offline, when on the train or such (where I am offline :)) but there is none for es6katas.org yet :(
