### ISSUE TITLE
Kata 52:Passing a value to the first next() call does NOT throw

### ISSUE THREAD

**Issue by serratus** [tddbin/es6katas.org#15]
First off, thanks for this collection of great katas, as they really help me get on track with ES6. 

While I was trying to finish the [send-value](http://tddbin.com/#?kata=es6/language/generator/send-value) kata on generators, I noticed an inconsistency: In the last example, the code should throw an error, but doesn't.
```javascript
it('passing a value to the first `next()` call throws', function() {
  function* generatorFunction() {
    yield 1;
    yield 2;
  }

  assert.throws(function() { generatorFunction().next('4343'); });
});
```

![6eac070acc9667481393207bab51f96c](https://cloud.githubusercontent.com/assets/1381822/8512845/ca786f02-2355-11e5-8d77-e5d0c600574d.png)

Even Mozilla [states](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Iterators_and_Generators) the following:  
> However, starting a newborn generator with any value other than undefined when calling next() will result in a TypeError exception.

But the example simply won't throw an error. I even tested it with babel deactivated on FF 39 and Chrome 43, but everything stays quiet.

Any ideas?

**Comment by wolframkriesing** [comment]
@serratus damn it, yeah i tried it too. I suppose it is an error in babel, because that used to work.
If someone has confirmation it would be cool to know. I didnt dig in there yet.

**Comment by wolframkriesing** [comment]
Ok, I read a lot of spec and articles now, it seems this was wrong behavior, I should have read the spec when I wrote this, sorry ... fixing it in a sec
    (Note: At the time of writing, nightlies of both Chrome and FF are fine, but other browsers may not yet be fully compliant and may incorrectly throw an error in this case).
is written in here http://davidwalsh.name/es6-generators

**Comment by wolframkriesing** [comment]
fixed in https://github.com/tddbin/katas/commit/0d7e8e22438fb2cd27fe3ef48e6c4e4efc8de615
thanks for reporting!

**Comment by serratus** [comment]
Thanks for fixing. That's what happens when an API matures ;-)
