### ISSUE TITLE
Class Katas more extends is the same as extends

### ISSUE THREAD

**Issue by Eschon** [tddbin/es6katas.org#17]
As the title says extends and more extends show the same code for me.

**Comment by wolframkriesing** [comment]
strange
can you please paste the links that are opened, the links shown on the es6katas page (you may right click and "copy link" or so) ... what browser are you using?

**Comment by Eschon** [comment]
This seems to be a weird issue with my browser cache. Suddenly everything that I clicked was the same es extends. The urls where always the right ones but the code was not.

I had a similar issue before where i had to open a Kata twice to get the right code but this time opening twice didn't help. Clearing my browser cache did it for me. Now I get the right code.

I'm using Safari 8.0.7 on OS X 10.10.4

**Comment by wolframkriesing** [comment]
maybe this did also solve it
https://github.com/tddbin/tddbin-frontend/issues/10
