### ISSUE TITLE
typeof Symbol() on Safari is 'object'

### ISSUE THREAD

**Issue by kasperekt** [tddbin/es6katas.org#18]
When I try to solve this problem in Safari 8:

```js
it('`typeof Symbol()` returns "symbol"', function(){
    const theType = typeof Symbol();
    assert.equal(theType, 'symbol');
});
```

`typeof Symbol()` returns `"object"`.

On Chrome it works fine. It looks like it just doesn't work on browsers without native `Symbol()` support.

**Comment by wolframkriesing** [comment]
I can confirm that ... mmmh, this is a Safari bug. Not sure I can do anything about it here, only maybe force babel's Symbol implementation over it but that would enforce it for all without any tricky detection :(
shall we wait? any idea?

**Comment by kasperekt** [comment]
When I tried Babel implementation of `Symbol()` it still worked the same. Maybe it's Babel bug?

**Comment by tddbin** [comment]
here is the solution to it
https://twitter.com/sebmck/status/621066934449213440

--
Kind regards / Saludos / Mit freundlichen Grüßen
Wolfram Kriesing, uxebu Co-Founder

kriesing@uxebu.com, mobile: +49 174 300 4595

ECMAScript6+React.js workshop http://meetu.ps/2Jds4D
Learn ES6, one kata a day http://es6katas.org

uxebu GmbH
Goethestraße 28
86161 Augsburg

Amtsgericht Augsburg, Handelsregister HRB 28613
Directors: W. Kriesing, T. v. Klipstein

**Comment by wolframkriesing** [comment]
should be deployed every second ... just pushed the fix, see
https://github.com/tddbin/tddbin-frontend/commit/53ba5d2620ebdb9c6744390e09b1b20ffc7d7a34
