### ISSUE TITLE
Website down?

### ISSUE THREAD

**Issue by impressivewebs** [tddbin/es6katas.org#27]
This doesn't work anymore?

http://es6katas.org/

**Comment by wolframkriesing** [comment]
works here, could you try again please?

**Comment by wolframkriesing** [comment]
oh sorry, the domain is moving right now, i am updating DNS stuff 
meanwhile feel free to use http://tddbin.github.io/es6katas.org/ which is the same

**Comment by impressivewebs** [comment]
Oh I see ok.. yeah, I saw that "coming soon" page, that's why I thought it was down.

Is the github URL eventually going to redirect to the main one? I'm doing a "learning tools" issue of my newsletter for this week (http://webtoolsweekly.com/) and I was going to include your Katas site. Should I include it with the github URL? Or is it better to wait until you have the DNS stuff straightened out?

**Comment by wolframkriesing** [comment]
things are slowly coming back to work, i guess it will be all back to normal tonight.
currently katas.tddbin.com is the only one that is processing, all others are coming back already, depending on the DNS cache used, of course :)
if you are sending out the newsletter today you might not want to include it, could you postpone it then?
sorry for the inconvinience

**Comment by impressivewebs** [comment]
It's ok, I'll include it in a future issue instead. Thanks!

**Comment by wolframkriesing** [comment]
everything seems to be working again. i am closing this one, please report if different. thanks for pointing it out.
