### ISSUE TITLE
Warnings

### ISSUE THREAD

**Issue by tobireif** [tddbin/es6katas.org#3]
On the "with-arrays" / "spread with arrays" page, there are several warnings, eg "Expected an identfier ...".

Perhaps it would be nice to start with a page without warnings? (where the assertions fail, but the code runs without warnings.)

**Comment by tddbin** [comment]
Thanks for reporting, I think they are due to ACE not implementing those
ES6 syntax. But I can only guess now, I am offline (kinda) ;)
Am 02.05.2015 14:59 schrieb "Tobi Reif" <notifications@github.com>:

**Comment by wolframkriesing** [comment]
Thanks for pushing me to it again, I updated ACE to 1.1.9 which removes most of them. Would be awesome if you can confirm and close this issue. Thanks a lot.
See https://github.com/tddbin/tddbin-frontend/commit/b2a07cddd4324208a5f803935729f416f7a44855

**Comment by tobireif** [comment]
Thanks for working on this!
On "spread""with-arrays", one warning warning is left, in line 20:
"Empty array elements require elision=true."
(I checked a few pages, but not all.)

**Comment by wolframkriesing** [comment]
that error actually goes away when you fix the kata :) so its kinda ok ...
though ACE should not complain.
Thanks for checking!

--
Kind regards / Saludos / Mit freundlichen Grüßen
Things we think are important http://www.uxebu.com/universe/
Meet uxebus at http://www.uxebu.com/about-us/events/

Wolfram Kriesing, CTO
uxebu

kriesing@uxebu.com, mobile: +49 174 300 4595

uxebu GmbH
Fraunhofer Straße 31e
86167 Augsburg

Amtsgericht Augsburg, Handelsregister HRB 28613
Directors: W. Kriesing, T. v. Klipstein

**Comment by tobireif** [comment]
I had fixed it :) but it still would be nice if there'd be no warnings on page load.

**Comment by wolframkriesing** [comment]
mmmh, it's a jshint setting.
If you add
```
   // jshint elision: true
```
at the top of the file it will disappear.
Maybe that's an idea for a future feature or preferences?
What do you think?

--
Kind regards / Saludos / Mit freundlichen Grüßen
Things we think are important http://www.uxebu.com/universe/
Meet uxebus at http://www.uxebu.com/about-us/events/

Wolfram Kriesing, CTO
uxebu

kriesing@uxebu.com, mobile: +49 174 300 4595

uxebu GmbH
Fraunhofer Straße 31e
86167 Augsburg

Amtsgericht Augsburg, Handelsregister HRB 28613
Directors: W. Kriesing, T. v. Klipstein

**Comment by tobireif** [comment]
> Maybe that's an idea for a future feature or preferences? What do you think?

Elision is legal, so yes, if you want to use elision in the code, setting JSHint elision:true would make sense, I think.
