### ISSUE TITLE
Reflect.apply throwing TypeError CreateListFromArrayLike due to wrong assert

### ISSUE THREAD

**Issue by protron** [tddbin/es6katas.org#31]
Line 15 of http://tddbin.com/#?kata=es6/language/reflect/apply has this wrong assert:

```
assert.equal(Reflect.apply(fn), 42);
```

I think that assert can never be fulfilled because the arguments of Reflect.apply seem to be all mandatory: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Reflect/apply

So I was able to pass the test after doing the proper modification in the line above and then changing that assert into:

```
assert.equal(Reflect.apply(fn, undefined, []), 42);
```

**Comment by wolframkriesing** [comment]
I worked on the reflect kata quite a bit today, please reopen in case this is still broken, thanks.
https://github.com/tddbin/katas/pull/44
