### ISSUE TITLE
Class extends : TypeError: function is not a function

### ISSUE THREAD

**Issue by ragmha** [tddbin/es6katas.org#32]
```
  it('class can extend `null`, not an instance of Object', () => {
      class NullClass extends null {}

      let nullInstance = new NullClass();
      assert.equal(nullInstance instanceof Object, false);
    });
```

- Seems to be working on http://tddbin.com/

- Throwing TypeError here(https://jsbin.com/famiyin/edit?js,output)

Am I missing something?

**Comment by andfinally** [comment]
I'm getting `TypeError: Super constructor null of NullClass is not a constructor` on http://tddbin.com/ with the same solution.

**Comment by wolframkriesing** [comment]
I went over all class katas again and I believe this problem is fixed, feel free to reopen the issue if that's not the case. Thx
See http://tddbin.com/#?kata=es6/language/class/extends
