### ISSUE TITLE
Exercise #25 is not completely solvable due to Firefox- and Chrome-bug

### ISSUE THREAD

**Issue by moritz439** [tddbin/es6katas.org#33]
Test _'class can extend `null`, not an instance of Object'_ on line 22 is not solvable because of this 
[https://bugs.chromium.org/p/v8/issues/detail?id=5115](url)
and this 
[https://bugzilla.mozilla.org/show_bug.cgi?id=1317391](url)
bug.

**Comment by wolframkriesing** [comment]
When "Transpile to ES5" is off it seems not solvable, but using babel ("Transpile to ES5" on) it is solvable. So we have to wait a bit for the engines to make it work there.
