### ISSUE TITLE
Exercise #69 tests 14/15 fails with exception

### ISSUE THREAD

**Issue by ohookins** [tddbin/es6katas.org#35]
`      it('when no property name is given (since no property has been added)', function() {
`

Apparently the solution is expected to be only passing the object on which to define the property, but giving a property name value of _anything_ (rather than only giving one argument) seems to work. Therefore you either get `true` returned from `Reflect.defineProperty` or you get a `TypeError` exception. It seems impossible to get false back.

Same goes for test 15 with a missing 3rd argument.

**Comment by wolframkriesing** [comment]
thanks for reporting!
