### ISSUE TITLE
What can I use this for 

### ISSUE THREAD

**Issue by sebs** [tddbin/es6katas.org#36]
Per Kata: 

1. little makdown file or other data struct 
2. display under test results.

Example
```
* [tricks with Symbol ion es6](#link)
* [Symbol (Programming) - Wikipedia](#link)
```

I send es6 newbies  often directly to es6-katas bootcamp and this would give them and insight why you would use something like that ;) which is  then motivation.

**Comment by wolframkriesing** [comment]
Are you looking for info like [those that I maintain in a JSON file][meta] or rather something more highlevel?

[meta]: https://github.com/tddbin/katas/blob/master/katas/es6/language/__raw-metadata__.js#L833-L876

**Comment by sebs** [comment]
stuff like this. Just a general hint of some links for  someone who might be lost in new stuff that is not so obvious

**Comment by wolframkriesing** [comment]
I would be interested in more examples, to understand better what you mean. PRs welcome too, makes it easier to embed it I guess ... thx for hint!

**Comment by wolframkriesing** [comment]
I tended to write more "basics" katas, like [this one for Map](https://github.com/tddbin/katas/blob/master/katas/es6/language/map/basics.js) which should give kinda feeling what this might be used for

**Comment by wolframkriesing** [comment]
i assume this is solved, feel free to reopen if you want to continue the discussion, thanks
