### ISSUE TITLE
Babel JS transpile error

### ISSUE THREAD

**Issue by tobireif** [tddbin/es6katas.org#5]
When I load http://es6katas.org/ and click on "creation", on "http://tddbin.com/#?" there is this message on the right:

```
Syntax or ES6 (babeljs) transpile error

SyntaxError: unknown: Unexpected token (9:4)
   7 |     class TestClass
   8 |     
>  9 |     const instance = new TestClass();
     |     ^
  10 |     assert.equal(typeof instance, 'object');
  11 |   });
  12 | 
```

And on the left there are many error/warning icons.

**Comment by tddbin** [comment]
Hi Tobi,

yep. Actually that is the task, to fix the code. And hopefully learn along
the way.
I thought it was a good way to do that this way, it's hard core I agree :)

--
Kind regards / Saludos / Mit freundlichen Grüßen
Wolfram Kriesing, uxebu Co-Founder

kriesing@uxebu.com, mobile: +49 174 300 4595

ECMAScript6+React.js workshop http://meetu.ps/2Jds4D
Learn ES6, one kata a day http://es6katas.org

uxebu GmbH
Fraunhofer Straße 31e
86167 Augsburg

Amtsgericht Augsburg, Handelsregister HRB 28613
Directors: W. Kriesing, T. v. Klipstein

**Comment by tobireif** [comment]
Hi Wolfram

I'm aware of the objective for the user on http://es6katas.org , and I did enjoy making the tests pass on http://tddbin.com/#?kata=es6/language/destructuring/array etc.

Regarding this specific page http://tddbin.com/#?kata=es6/language/class/creation (and other pages with warning/error icons on the left):

Some of the many error/warning icons on the left side of the page might be real issues to be fixed by you guys, see eg #3 "I updated ACE to 1.1.9 which removes most of the [error messages / warnings]".

It would be great if there'd be no error messages / warnings on the left side (no syntax errors etc). Then there would only be the failed-test messages in the area on the right, as a clear list of issues to be fixed by the user.

If there are no issues to be fixed by you guys, on none of the pages (in this case please close this report), I'll try to resolve everything myself :) (per session, as user)

Tobi

**Comment by tobireif** [comment]
Perhaps this could be an option:

On http://tddbin.com/#?kata=es6/language/class/creation in the test named "has a simplified syntax", instead of `class TestClass` have `class Foo {}`. This would get rid of all errors. All failed-test messages would get listed -> the user could start making the tests pass without wondering whether the Babel JS transpile error and the many error messages on the left mean that the page is broken :)

**Comment by tobireif** [comment]
Potential improvements could include my suggestion above, or adding a comment to the JS, eg "The Babel JS transpile error and the error messages on the left don't mean that the web app is broken :)"

These might be potential improvements. Regarding real issues:

There are no issues (changing the JS makes all errors disappear), please feel free to close this report.

**Comment by wolframkriesing** [comment]
Hi Tobi, I left this open, because I basically was really thinking about it a lot. And I think the way you are suggesting is the way to go. It would actually mean to enhance the test runner to be more supportive in finding the root cause. I just couldn't decide. I would like open a different issue that basically breaks it down to "Make the reporter more supportive, better in finding out what to do".
Since I tried esp. in this kata to make the user focus on how to use the class syntax, in this case just add the `{}` behind `class TestClass` I think the test should be as it is, just the reporter is not helpful. Right?
I will add this hint, as you suggest, that's a great first way to do it. Thanks for your resistence.

**Comment by wolframkriesing** [comment]
If you think this is cool, https://github.com/tddbin/tddbin-frontend/commit/b473465b981519631c149b9281eed2a1480a2aaf
feel free to close this issue. Thanks a lot!

**Comment by tobireif** [comment]
>  in this case just add the {} behind class TestClass

I know :)

It now is OK with the hint you added, the user won't think the whole web app is broken and can try to make the tests green, so I'm closing this issue.

**Comment by wolframkriesing** [comment]
thanks

--
Kind regards / Saludos / Mit freundlichen Grüßen
Wolfram Kriesing, uxebu Co-Founder

kriesing@uxebu.com, mobile: +49 174 300 4595

ECMAScript6+React.js workshop http://meetu.ps/2Jds4D
Learn ES6, one kata a day http://es6katas.org

uxebu GmbH
Fraunhofer Straße 31e
86167 Augsburg

Amtsgericht Augsburg, Handelsregister HRB 28613
Directors: W. Kriesing, T. v. Klipstein

**Comment by wolframkriesing** [comment]
I got this feedback again, so I did really change it, how do you like https://github.com/tddbin/katas/commit/aad517992f399f189ffee128f653a25a00bd61fd ?

**Comment by tobireif** [comment]
One of my suggestions was "instead of class TestClass have class Foo {}. This would get rid of all errors" ... and the syntax would be there already.

Regarding https://github.com/tddbin/katas/commit/aad517992f399f189ffee128f653a25a00bd61fd :
Having the syntax in the hint is even better than my above suggestion.
But whether the "let" (to be deleted by the user) will confuse people remains to be seen :)

**Comment by tobireif** [comment]
BTW, I don't think the "let" is an issue.
