### ISSUE TITLE
Link to documentation/spec

### ISSUE THREAD

**Issue by akoskm** [tddbin/es6katas.org#8]
I started with the Array API and I have to admit that the destructuring test wasn't that obvious. Fortunately there were some [Object destructuring](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment#Object_destructuring) examples on MDN.

Could we have somewhere in the tests or on the ES6 Katas page link to the relevant documentation from MDN (I know it's not official spec but it could be helpful).

Also, I feel that 5. `[].entires` test requires knowledge from Desctructuring.

**Comment by wolframkriesing** [comment]
Links to docs would make perfect sense in here https://github.com/tddbin/katas/blob/master/katas/es6/language/__raw-metadata__.js which is used to generate the es6katas page. What do you think?

The dependencies for a kata are also listed there, unfortunately not listed on es6katas site yet.
PRs welcome

**Comment by akoskm** [comment]
Yes, that's exactly what I thought. I'll try to wrap up a pull request this week.

**Comment by akoskm** [comment]
I was able to build `https://github.com/tddbin/katas`, the test are passing, but how I supposed to start the application?
I see no run scripts just a `build-for-offline.sh` which doesn't work on Linux.

If you could give me some directions about what should be done for Linux maybe I can include that too.

**Comment by wolframkriesing** [comment]
does this help your initial problem with the array destructuring kata?
https://github.com/tddbin/katas/commit/ecbc589c55b01fbadcd3b081b71ac39e1fcd0af2

btw I am adding links now, feel free to add more, just not using them anywhere :)
https://github.com/tddbin/katas/commit/bdc1ac549a500df6957108cfbcd34902bd34cfc5

oh, re building, could you move this to a separate issue? actually I never tried but had the intention that it works on linux :(

**Comment by akoskm** [comment]
The links structure is cool and I like the idea of discussion for every kata.

I can't say that your comment will help or not for those who are new to destructuring, since I'm already familiar with it and I know "what to look for".

In my opinion, from one example, somebody new to destructuring not necessarily will understand it. The more examples you see the easier will be to understand the concept. MDN has lots of examples so I would prefer a link to their site.

I opened an issue regarding the build process on Linux: https://github.com/tddbin/es6katas.org/issues/13.
